### ISSUE TITLE
python-snap7: OSError: [WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by supportNCL** [LiuYuancheng/PLC_and_RTU_Simulator#3]
**OS Platform** : Windows 

**Error message**: 

```
OSError: [WinError 193] %1 is not a valid Win32 application
```

Snap7 download link: https://sourceforge.net/projects/snap7/

Python version 3.12 64bit.

**Comment by LiuYuancheng** [comment]
This may because the snap7 dll file(205K 32/64 bit multi-platform Ethernet S7 PLC communication suite) may not work correct in some 64 bit system, you can down load the pure 64 bit system dll from this link and that will solve the problem.

https://github.com/LiuYuancheng/PLC_and_RTU_Simulator/tree/main/S7Comm_RTU_Simulator/WinOS_dll/64bit

For 32bit dll, you can download from this link:

https://github.com/LiuYuancheng/PLC_and_RTU_Simulator/tree/main/S7Comm_RTU_Simulator/WinOS_dll

Then you can solve the problem.

**Comment by supportNCL** [comment]
Problem solved !
